### ISSUE TITLE
ERROR] The target platform you're using does not have network configuration pre-implemented.

### ISSUE THREAD

**Issue by krunalchauhan637** [AVSystem/Anjay-mbedos-client#1]
![Anjay-mbedos-client](https://user-images.githubusercontent.com/59273222/143178843-94bd6cd1-cd16-47e4-beed-3d6d955fe6d9.png)

Hi , 

Board: NUCLEO_F429ZI
I am using  Anjay-mbedos-client for demo purpose for my device.
NUCLEO_F429ZI board have internet connectivity via ethernet. 
But as I can see this example have only cellular connectvity support.

What should I do enable ethernet connectivity/ Add Support for ethernet in this sdk ??

**Comment by kFYatek** [comment]
Hi,

You can get the Ethernet interface on that board to work by removing the configuration option that unconditionally sets the default interface type to cellular:

```diff
--- a/mbed_app.json
+++ b/mbed_app.json
@@ -16,8 +16,7 @@
       "platform.stdio-baud-rate": 115200,
       "platform.stdio-convert-newlines": 1,
       "target.OUTPUT_EXT": "bin",
-      "target.app_offset": "0x10000",
-      "target.network-default-interface-type": "CELLULAR"
+      "target.app_offset": "0x10000"
     },
     "DISCO_L496AG": {
       "stmod_cellular.provide-default": "true",
```

This fix will be committed to this repository in the near future as well.

Please note that this (i.e., Anjay-mbedos-client) repository is only intended as a demo application for testing and reference purposes. If you want to build your own application, I recommend you to create a new Mbed OS project, using https://github.com/AVSystem/Anjay-mbedos as a dependency.

**Comment by krunalchauhan637** [comment]
Thanks for @kFYatek for quick for reply.
By doing above change, I am able to connect my device on Coiote IoT Device Management.
