### ISSUE TITLE
Sensor library uses old version

### ISSUE THREAD

**Issue by JanneKiiskila** [AVSystem/Anjay-mbedos-client#7]
The current version of the ST sensor library is a bit old, there's newer (though still old) version available.

https://os.mbed.com/teams/ST/code/X_NUCLEO_IKS01A2//rev/138a7a28bd21/

Is the latest available now.

**Comment by JanneKiiskila** [comment]
Even the latest one will not work with Mbed OS 6 due to the `wait_ms` function call, that should be if deffed out and `ThisThread:wait(10 ms)` should be used instead.

Raised a ticket about that; https://github.com/ARMmbed/mbed-os/issues/15198

**Comment by Mierunski** [comment]
If newer version is working, contributions are welcome

**Comment by JanneKiiskila** [comment]
https://github.com/AVSystem/Anjay-mbedos-client/pull/11 resolves that issue.
