### ISSUE TITLE
README.md refers to IKS02A1, while SW supports IKS01A2

### ISSUE THREAD

**Issue by JanneKiiskila** [AVSystem/Anjay-mbedos-client#9]
https://github.com/AVSystem/Anjay-mbedos-client/blob/master/README.md refers to an optional sensor board IKS02A1. However, the actual .lib file pulling in the drivers is meant for [IKS01A2](https://github.com/AVSystem/Anjay-mbedos-client/blob/master/X_NUCLEO_IKS01A2.lib).

This unfortunately means that most of the drivers will not work, as the chip IDs are not matching.

```
WARNING [humidity_obj] [./humidity.cpp:254]: Failed to initialize humidity sensor
WARNING [barometer_obj] [./barometer.cpp:251]: Failed to initialize barometer
```

You will get warnings like that.

Only magnetometer (object 3314) will be functional with an actual [IKS02A1](https://www.st.com/en/ecosystems/x-nucleo-iks02a1.html).

[IKS01A2](https://www.st.com/en/ecosystems/x-nucleo-iks01a2.html) is unfortunately out of production, so you cannot purchase it.

**Comment by JanneKiiskila** [comment]
The status for the IKS01A2 is actually somewhat interesting.
- https://www.digikey.co.uk/en/products/detail/stmicroelectronics/X-NUCLEO-IKS01A2/6558528?s=N4IgTCBcDaIJYGsDOAGAjAQwgXQL5A shows its clearly obsolete.
-  [STMs own page](https://www.st.com/en/ecosystems/x-nucleo-iks01a2.html#sample-buy) says it is active.
- Availability is quite low for all suppliers and delivery times are >50 weeks.

Someone from STM should confirm the real status.

My guess is that it's really becoming obsolete (edit: 31 Mar 2022).

**Comment by Kucmasz** [comment]
Since https://github.com/AVSystem/Anjay-mbedos-client/pull/10 was closed as being superseded by https://github.com/AVSystem/Anjay-mbedos-client/pull/11 and the correction was made in README, I will close this issue. Possible support for ISK02A1 would be another topic but it's not considered nor planned at the moment.
